# https://github.com/grafana/k6/blob/master/docker-compose.yml
---
version: "3.8"

#volumes:
#  esdata01:
#    driver: local

networks:
#  default:
#    name: elastic
#    external: false
  monitoring:
    name: monitoring
    external: false

services:
  k6:
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    image: grafana/k6:0.47.0
    command:
      - run
      - -o
      - experimental-prometheus-rw
      - /scripts/Buy-iPhone.js
    networks:
      - monitoring
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    volumes:
      - ./:/scripts
      - ./npmlibs:/scripts/npmlibs

  grafana:
    image: grafana/grafana:latest
    networks:
      - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
#      - ./dashboards:/var/lib/grafana/dashboards
#      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  prometheus:
    image: prom/prometheus:v2.47.2
    command:
      - '--enable-feature=remote-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    ports:
      - 9090:9090
