global:
  scrape_interval: 10s
  # external_labels
tracing:
  client_type: grpc
  endpoint: otel-collector:4317
  sampling_fraction: 1
  insecure: true
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'otel-collector'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'otel-collector:8888'
  - job_name: 'grafana'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'grafana:3000'
  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'node-exporter:9100'
#remote_write:
#  - url: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
#    # Sets the `Authorization` header on every remote write request with the
#    # configured username and password.
#    # password and password_file are mutually exclusive.
#    basic_auth:
#      username: 1271273
#      password: ""
